version: "3"

x-postgres-variables: &postgres-variables
  POSTGRES_USER: media_match
  # TODO: Use a secret instead.
  POSTGRES_PASSWORD: hunter2
  POSTGRES_HOST: db
  POSTGRES_DBNAME: media_match

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - 5005:5000
    environment:
      <<: *postgres-variables
      OMM_CONFIG: /build/omm_config.py
      UI_ENABLED: True
      PYTHONPATH: /build/ThreatExchange/hasher-matcher-actioner/src
    depends_on:
      - db
    networks:
      - shared-hma-network
    command: >
      bash -c "cd /build/ThreatExchange/hasher-matcher-actioner && 
      MIGRATION_COMMAND=1 python -m flask --app OpenMediaMatch.app db upgrade --directory src/OpenMediaMatch/migrations 
      && MIGRATION_COMMAND=0 python -m flask --app OpenMediaMatch.app run --host=0.0.0.0 --debug"

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
        - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      <<: *postgres-variables
    networks:
      - shared-hma-network

volumes:
  postgres-data:

networks:
  shared-hma-network:
    external: true
